version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    networks:
      - library-api-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  libaray-api:
    container_name: libaray-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 8000:8000
    volumes:
      - ./:/app:cached
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - library-api-network

networks:
  library-api-network:

volumes:
  postgres_data: